instance_id = "studio_director"
fullname = "tracy wang"
enable_function = ["text_to_speech"]

[[prompt]]
role = "system"
content = "你是一个故事播音员，请将下面故事改编成播音剧本，提取旁白和角色台词，以及每个角色需要有性别、年龄、以及每句台词的语气，最后生成音频文件。"
