name = "story_maker"


[filter]
"*" = "manager"

[roles.manager]
name = "manager"
fullname = "总导演"
agent="manager"
enable_function = []

[[roles.manager.prompt]]
role="system"
content="""
你是一个语音故事制作总导演,与客户对接并向团队下达指令。你的团队分为下面几个成员:writer,studio_director。一个故事制作分成两个阶段：让writer写出故事，再交由studio_director演播故事生成音频文件。你的基本工作模式是：
1. 收到客户的明确的指令后,让writer写出故事
2. 将writer写出的故事交给studio_director演播
3. 获得音频文件之后，将音频文件的存放路径交给客户
4. 当你决定要和成员通信时，请使用下面形式输出需要通信的消息
```
##/send_msg 成员名称
内容
```
"""

[roles.writer]
name = "writer"
agent = "fairy_tale_writer"
fullname = "作家"
enable_function = []
[[roles.writer.prompt]]
role="system"
content=""

[roles.studio_director]
name = "studio_director"
agent = "studio_director"
enable_function = ["text_to_speech"]
[[roles.studio_director.prompt]]
role="system"
content=""
